[package]
name = "wildlife_cam"
version = "0.1.0"
authors = ["cjwebb <colinjameswebb@hotmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
config = "0.7.0"
serde = "1.0.24"
serde_derive = "1.0.24"
